### ISSUE TITLE
anniversary: Error on device update!

### ISSUE THREAD

**Issue by GitHubxtsnl** [amaximus/anniversary#2]
- Anniversary sensor for upcoming events for Home Assistant version 0.0.1
- Home Assistant CORE 2021.8.8

1. installed Anniversary via HACS
2. manually added the config below to my configuration.yaml file

```
sensor:
  - platform: anniversary
    name: Anniversarys
    date_format: '%A %d %B %Y'
    multiple: true
    anniversaries:
      - event: 'name1'
        date: '1979-5-22'
        icon: mdi:face-man
      - event: 'name2'
        date: '2007-1-1'
        icon: mdi:face-man-outline
```

after a restart of HA the following appears in the log:

```
Logger: homeassistant.components.sensor
Source: custom_components/anniversary/sensor.py:57
Integration: Sensor (documentation, issues)
First occurred: 9:11:11 AM (1 occurrences)
Last logged: 9:11:11 AM

anniversary: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/config/custom_components/anniversary/sensor.py", line 149, in async_update
    anni_date_p = _get_anniversary_date(self, i, today_p.year)
  File "/config/custom_components/anniversary/sensor.py", line 57, in _get_anniversary_date
    mydate_p = datetime.strptime(self._anniversaries[i]['date'], self._date_format)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1979-5-22' does not match format '%A %d %B %Y'
```

**Comment by amaximus** [comment]
Newly created release (0.0.3) fixes this issue: if the date specified in the event does not correspond to the date_format, there will be no error, the event will be ignored and a warning message will be logged.

Please update the custom integration, test and get back to me with results.

**Comment by amaximus** [comment]
@GitHubxtsnl do you need further assistance with this issue or latest version solved the issue?
