### ISSUE TITLE
2024.11.0 HA update

### ISSUE THREAD

**Issue by VagnPetersen** [amaximus/anniversary#24]
After updating HA yesterday, anniversary is not working anymore:

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 09:18:54 (1 occurrences)
Last logged: 09:18:54

Setup failed for custom integration 'anniversaries': Unable to import component: No module named 'integrationhelper'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/anniversaries/__init__.py", line 6, in <module>
    from integrationhelper.const import CC_STARTUP_VERSION
ModuleNotFoundError: No module named 'integrationhelper'

**Comment by amaximus** [comment]
Something must be wrong on your side as it works as expected:
```
(ha_venv3_12) thin620t:~/homeassistant_conf $curl -s -H @hass_header.txt http://192.168.1.32:8123/api/states/sensor.current_version
{"entity_id":"sensor.current_version","state":"2024.11.1","attributes":{"friendly_name":"Current Version"},"last_changed":"2024-11-12T16:32:53.403134+00:00","last_reported":"2024-11-12T16:32:53.403134+00:00","last_updated":"2024-11-12T16:32:53.403134+00:00","context":{"id":"01JCGKH24VYZY09YG0RFHE50VS","parent_id":null,"user_id":null}}
(ha_venv3_12) thin620t:~/homeassistant_conf $curl -s -H @hass_header.txt http://192.168.1.32:8123/api/states/update.anniversary_update
{"entity_id":"update.anniversary_update","state":"off","attributes":{"auto_update":false,"display_precision":0,"installed_version":"0.3.1","in_progress":false,"latest_version":"0.3.1","release_summary":null,"release_url":"https://github.com/amaximus/anniversary/releases/0.3.1","skipped_version":null,"title":null,"update_percentage":null,"entity_picture":"https://brands.home-assistant.io/_/anniversary/icon.png","friendly_name":"Anniversary update","supported_features":23},"last_changed":"2024-11-12T16:32:52.516841+00:00","last_reported":"2024-11-12T16:32:52.516841+00:00","last_updated":"2024-11-12T16:32:52.516841+00:00","context":{"id":"01JCGKH1943TAHKDBF280C6RQG","parent_id":null,"user_id":null}}
(ha_venv3_12) thin620t:~/homeassistant_conf $curl -s -H @hass_header.txt http://192.168.1.32:8123/api/states/sensor.events
{"entity_id":"sensor.events","state":"20","attributes":{"events":[{"event_on":"2024-12-02","icon":"mdi:cake-variant","type":"event","event":"Éva","event_in":"20","anniversary":"80"},{"event_on":"2024-12-24","icon":"mdi:calendar","type":"event","event":"Éva nap","event_in":"42","anniversary":"None"},{"event_on":"2024-12-27","icon":"mdi:calendar","type":"event","event":"János nap","event_in":"45","anniversary":"None"},{"event_on":"2025-01-15","icon":"mdi:cake-variant","type":"event","event":"Ákos","event_in":"63","anniversary":"21"},{"event_on":"2025-01-22","icon":"mdi:cake-variant","type":"event","event":"János","event_in":"70","anniversary":"19"},{"event_on":"2025-01-27","icon":"mdi:cake-variant","type":"event","event":"Kristóf","event_in":"75","anniversary":"19"},{"event_on":"2025-02-16","icon":"mdi:calendar","type":"event","event":"Julianna-nap","event_in":"95","anniversary":"None"},{"event_on":"2025-03-11","icon":"mdi:cake-variant","type":"event","event":"Kriszti","event_in":"119","anniversary":"51"},{"event_on":"2025-04-11","icon":"mdi:cake-variant","type":"event","event":"Attila","event_in":"150","anniversary":"56"},{"event_on":"2025-04-15","icon":"mdi:cake-variant","type":"event","event":"Tamás","event_in":"154","anniversary":"25"},{"event_on":"2025-04-16","icon":"mdi:cake-variant","type":"event","event":"Misi","event_in":"155","anniversary":"70"},{"event_on":"2025-04-18","icon":"mdi:cake-variant","type":"event","event":"Juli","event_in":"157","anniversary":"58"},{"event_on":"2025-04-25","icon":"mdi:cake-variant","type":"event","event":"Eni","event_in":"164","anniversary":"53"},{"event_on":"2025-07-05","icon":"mdi:ring","type":"event","event":"Házassági","event_in":"235","anniversary":"28"},{"event_on":"2025-07-21","icon":"mdi:cake-variant","type":"event","event":"Reni","event_in":"251","anniversary":"25"},{"event_on":"2025-08-05","icon":"mdi:calendar","type":"event","event":"Krisztina nap","event_in":"266","anniversary":"None"},{"event_on":"2025-08-10","icon":"mdi:ring","type":"event","event":"Házassági","event_in":"271","anniversary":"28"},{"event_on":"2025-09-15","icon":"mdi:calendar","type":"event","event":"Enikő nap","event_in":"307","anniversary":"None"}],"first_event_name":"Éva","first_event_in":"20","first_event_on":"2024-12-02","anniversary":"80","icon":"mdi:cake-variant","friendly_name":"events"},"last_changed":"2024-11-12T16:32:39.285863+00:00","last_reported":"2024-11-12T16:32:39.285863+00:00","last_updated":"2024-11-12T16:32:39.285863+00:00","context":{"id":"01JCGKGMBNPV5J7M1FX2QQWT47","parent_id":null,"user_id":null}}
(ha_venv3_12) thin620t:~/homeassistant_conf $
```

Please double-check that you are using the latest version of the integration.
